name: book
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  curved_navigation_bar: ^1.0.3
  google_fonts: ^3.0.1
  smooth_page_indicator: ^1.0.0+2
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  dio: ^4.0.6
  conditional_builder_null_safety: ^0.0.6
  url_launcher: ^6.1.5
  animated_bottom_navigation_bar: ^1.0.1
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/profile/
    - assets/images/common/
    - assets/images/books/
    - assets/images/login/
    - assets/images/onBoarding/